services:
    digital_ocean_v2.adapter:
        class: DigitalOceanV2\Adapter\GuzzleHttpAdapter
        arguments: ['%digital_ocean_access_token%']
        public: false

    digital_ocean_v2.api:
        class: DigitalOceanV2\DigitalOceanV2
        arguments: ['@digital_ocean_v2.adapter']
        public: false

    guzzle_http.client:
        class: GuzzleHttp\Client
        public: false

    ip_resolver:
        class: DnsUpdater\Service\IpResolver\CanIHazIpResolver
        arguments: ['@guzzle_http.client']
        public: false

    record_persister:
        class: DnsUpdater\Service\RecordPersister\DigitalOceanAdapter
        arguments: ['@digital_ocean_v2.api']
        public: false

    cache:
        class: Symfony\Component\Cache\Simple\FilesystemCache
        public: false

    dns_update_command:
        class: DnsUpdater\Console\DnsUpdateCommand
        arguments:
            - '@ip_resolver'
            - '@record_persister'
            - '@cache'
            - '@logger'
            - '%domains%'
