services:
    digital_ocean_v2.adapter:
        class: DigitalOceanV2\Adapter\GuzzleHttpAdapter
        arguments: ['%digital_ocean_access_token%']
        public: false

    digital_ocean_v2.api:
        class: DigitalOceanV2\DigitalOceanV2
        arguments: ['@digital_ocean_v2.adapter']
        public: false

    guzzle_http.client:
        class: GuzzleHttp\Client
        public: false

    ip_resolver:
        class: DnsUpdater\Service\CanIHazIpResolver
        arguments: ['@guzzle_http.client']
        public: false

    update_record_repository:
        class: DnsUpdater\Repository\DigitalOceanAdapter
        arguments: ['@digital_ocean_v2.api']
        public: false

    cache:
        class: Symfony\Component\Cache\Simple\FilesystemCache
        public: false

    update_record:
        class: DnsUpdater\Command\UpdateRecord
        arguments:
            - '@ip_resolver'
            - '@update_record_repository'
            - '@cache'
            - '@logger'
        public: false

    dns_update_command:
        class: DnsUpdater\Console\DnsUpdateCommand
        arguments:
            - '@update_record'
            - '%domain%'
            - '%hosts%'
