name: tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Installing PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: '7.1'
        coverage: xdebug
    - name: Install dependencies
      run: make vendor
    - name: Run tests & publish code coverage
      uses: paambaati/codeclimate-action@v2.3.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make ci
        debug: true
